// frontend/src/_components/cv/website/Hobbies.tsx
import Hobby, { HobbyProp } from "./Hobby";

export default function Hobbies({hobbies}: any) {
  return <section id="loisirs">
    <div className="title">
      <h2>Loisirs</h2>
    </div>
    <div className="element-list">
      {hobbies.map((hobby: HobbyProp) =>
        <Hobby key={hobby.title} props={hobby} />
      )}
    </div>
  </section>
}

// frontend/src/app/_components/cv/website/hobbies/hobbies.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-hobbies',
    imports: [
        CommonModule
    ],
    templateUrl: './hobbies.component.html',
    styleUrl: './hobbies.component.scss'
})
export class HobbiesComponent {
    @Input('hobbies') hobbies: any;
}

<section id="loisirs">
    <div class="title">
        <h2>Loisirs</h2>
    </div>
    <div class="element-list">
        @for(hobby of hobbies; track hobby.title) {
            <app-hobby [hobby]="hobby"/>
        }
    </div>
</section>
