// frontend/src/_components/cv/website/Trainings.tsx
import Training, { TrainingProp } from "./Training";

export default function Trainings({ trainings }: any) {
  return <section id="formations">
    <div className="title">
      <h2>Formations et Diplômes</h2>
    </div>
    <ul>
      {trainings.map((training: TrainingProp) => {
        if (training.isDisplay)
          return <Training key={training.title} props={training} />
      })}
    </ul>
  </section>
}

// frontend/src/app/_components/cv/website/trainings/trainings.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

import { TrainingComponent } from '../training/training.component';

@Component({
    selector: 'app-trainings',
    imports: [
        CommonModule,
        TrainingComponent
    ],
    templateUrl: './trainings.component.html',
    styleUrl: './trainings.component.scss'
})
export class TrainingsComponent {
    @Input('trainings') trainings: any;
}

<section id="formations">
    <div class="title">
        <h2>Formations et Diplômes</h2>
    </div>
    <ul>
        @for(training of trainings; track training.title) {
            @if (training.isDisplay) {
                <app-training [training]="training" />
            }
        }
    </ul>
</section>
