// frontend/src/_components/Project.tsx
export interface ProjectProp {
  idProject: number;
  title: string;
  link: string;
  image: string;
  description: string;
  visibility: boolean;
  inProgress: boolean;
}

export default function Project({ props }: { props: ProjectProp }) {
  return <div className='card'>
    <img className='card-img-top' src={props.image} alt={'Image représentant le project ' + props.title} />
    <div className='card-body'>
      <h5 className='card-title md-2'>{props.title} {props.inProgress ? <span className='badge bg-info'>En cours</span> : null}</h5>
      <p className='card-text'>{props.description}</p>
      <p className='link text-right'>
        <a className={'btn btn-danger' + (props.inProgress ? ' disabled' : '')} href={props.link} target='_blank'>Voir le site</a>
      </p>
    </div>
  </div>
}

// frontend/src/app/_components/projects/project-item/project.component.ts
import { Component, Input } from '@angular/core';

import { ProjectLinkComponent } from "../project-link/project-link.component";

@Component({
  selector: 'app-project',
  imports: [
    ProjectLinkComponent
  ],
  standalone: true,
  templateUrl: './project.component.html',
  styleUrl: './project.component.scss'
})
export class ProjectComponent {
  @Input('project') projectData: any;
}

<div class="card">
	<img class="card-img-top" [src]="projectData.image" [alt]="'Image représentant le projet ' + projectData.title" />

	<div class="card-body">
		<h5 class="card-title md-2">
			{{ projectData.title }}
			<span *ngIf="projectData.inProgress" class="badge bg-info">En cours</span>
		</h5>

		<p class="card-text">{{ projectData.description }}</p>

		<p class="link text-right">
			<app-project-link [link]="projectData.link" />
		</p>
	</div>
</div>
