// frontend/src/_components/projects/WebSite.tsx
import { faArrowUpRightFromSquare } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export interface WebSiteProp {
  title: string;
  link: string;
  image: string;
  description: string;
  technologies: any[];
  isDisplay: boolean;
  inProgress: boolean;
}

export default function WebSite({ props }: { props: WebSiteProp }) {
  return <a className="website" href={props.link} title={props.title} target="_blank">
    <div className="website-image">
      <img src={props.image} alt="" />
    </div>
    <div className="website-title">{props.title}</div>
    <div className="website-tehnologies">
      {props.technologies.map((techno: string) => {
        return <span>{techno}</span>
      })}
    </div>
    <div className="website-link">
      <FontAwesomeIcon icon={faArrowUpRightFromSquare} />
    </div>
  </a>
}

// frontend/src/app/_components/projects/website/website.component.ts
import { Component } from '@angular/core';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faArrowUpRightFromSquare } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-website',
  imports: [
    FontAwesomeModule
  ],
  templateUrl: './website.component.html',
  styleUrl: './website.component.scss'
})
export class WebsiteComponent {
  faArrowUpRightFromSquare = faArrowUpRightFromSquare
}

<a class="website" href={props.link} title={props.title} target="_blank">
    <div class="website-image">
        <img src={props.image} alt="" />
    </div>
    <!-- <div class="website-title">{props.title}</div> -->
    <div class="website-tehnologies">
        <!-- {props.technologies.map((techno: string) => {
        return <span>{techno}</span>
        })} -->
    </div>
    <div class="website-link">
        <fa-icon [icon]="faArrowUpRightFromSquare"></fa-icon>
    </div>
</a>
