// frontend/src/_components/cv/website/Skills.tsx
import { useContext, useRef } from "react";
import Skill, { SkillProp } from "./Skill";
import { CvAnimationContext } from "../../../_hooks/useCvAnimation";
import { AnimatePresence, motion } from "framer-motion";

export default function Skills({ skills }: any) {
  const ref = useRef(null);
  const { currentElement, setCurrentElement } = useContext(CvAnimationContext);

  const animVariants = {
    visible: { height: "auto" },
    hidden: { height: "0" }
  };

  return <section id="competences">
    <div className="title">
      <h2>Compétences</h2>
    </div>
    <ul>
      {skills.map((skill: SkillProp) => {
        if (skill.isDisplay)
          return <Skill key={skill.content[0].text} props={skill} />
      })}

      <li className="cv-block" onClick={() => setCurrentElement(ref.current)} ref={ref}>
        <div className="cv-item">
          <span className="content">Autres outils <button className="btn btn-sm btn-danger">+</button></span>
        </div>
        <AnimatePresence mode="popLayout">
          <motion.div variants={animVariants} animate={currentElement == ref.current ? 'visible' : 'hidden'} initial='hidden' exit='hidden' style={{overflow:"hidden"}}>
            <div className="cv-detail card">
              <div className="card-body">
                <p>
                  <b>Logiciels graphiques:</b> Photoshop CS6, Gimp, Paint<br />
                  <b>Logiciels de modélisation 3D:</b> Blender<br />
                  <b>Logiciels de CAO:</b> FreeCAD, AutoDesk Fusion 360, SolidWorks<br />
                  <b>Logiciels de montage vidéo:</b> Premiere Pro, After Effect, DaVinci Resolve<br />
                  <b>Logiciels de bureautique:</b> Suite Microsoft Office (Word, Excel, PowerPoint)
                </p>
              </div>
            </div>
          </motion.div>
        </AnimatePresence>
      </li>
    </ul>
  </section>
}

// frontend/src/app/_components/cv/website/skills/skills.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-skills',
    imports: [
        CommonModule
    ],
    templateUrl: './skills.component.html',
    styleUrl: './skills.component.scss'
})
export class SkillsComponent {
    @Input('skills') skills: any;
}

<section id="competences">
    <div class="title">
        <h2>Compétences</h2>
    </div>
    <ul>
        @for(skill of skills; track skill.title) {
            @if(skill.isDisplay) {
                <app-skill [skill]="skill" />
            }
        }

        <li class="cv-block">
            <div class="cv-item">
                <span class="content">Autres outils <button class="btn btn-sm btn-danger">+</button></span>
            </div>
            <div class="cv-detail card">
                <div class="card-body">
                    <p>
                        <b>Logiciels graphiques:</b> Photoshop CS6, Gimp, Paint<br />
                        <b>Logiciels de modélisation 3D:</b> Blender<br />
                        <b>Logiciels de CAO:</b> FreeCAD, AutoDesk Fusion 360, SolidWorks<br />
                        <b>Logiciels de montage vidéo:</b> Premiere Pro, After Effect, DaVinci Resolve<br />
                        <b>Logiciels de bureautique:</b> Suite Microsoft Office (Word, Excel, PowerPoint)
                    </p>
                </div>
            </div>
        </li>
    </ul>
</section>
