// frontend/src/app/_components/layouts/footer/footer.component.ts
import { DatePipe } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  imports: [
    DatePipe
  ],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss'
})
export class FooterComponent {
  title: string = 'flyarts.fr';
  date: Date = new Date();
}

<footer className="container">
    <div className="row">
        <div className="col-md-12">
            <p id="footer_copyright">
                Copyright &copy; {{ date | date:'yyyy' }} {{ title }} | Tous droits réservés | Développeur et Webmaster:
                Florent LAVIGNOTTE
            </p>
        </div>
    </div>
</footer>

// frontend/src/_components/layouts/Footer.tsx
function Footer() {
  return <footer className="container">
    <div className="row">
      <div className="col-md-12">
        <p id="footer_copyright">
          Copyright &copy; { /* date("Y") */} flyarts.fr | Tous droits réservés | Développeur et Webmaster: Florent LAVIGNOTTE
        </p>
      </div>
    </div>
  </footer>
}

export default Footer
