// frontend/src/app/_components/layouts/header/header.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { RouterLink } from '@angular/router';

declare var bootstrap: any;

@Component({
  selector: 'app-header',
  imports: [
    RouterLink
  ],
  standalone: true,
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {
  @ViewChild('mainMenu') mainMenuRef!: ElementRef;

  closeNavbar() {
    const menuEl = this.mainMenuRef.nativeElement;

    if (menuEl.classList.contains('show')) {
      if (typeof bootstrap !== 'undefined') {
        const bsCollapse = bootstrap.Collapse.getInstance(menuEl) || new bootstrap.Collapse(menuEl);
        bsCollapse.hide();
      } else {
        menuEl.classList.remove('show');
      }
    }
  }
}

<header>
    <nav className="navbar navbar-expand-lg navbar-dark">
        <div className="container-fluid">
            <a class="navbar-brand" [routerLink]="['/']">FlyArts</a>

            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainMenu"
                aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
            </button>

            <div id="mainMenu" className="collapse navbar-collapse">
                <div className="me-auto mb-2 mb-lg-0"></div>
                <ul className="navbar-nav d-flex">
                    <li className="nav-item">
                        <a class="nav-link" title="Accueil du site FlyArts" [routerLink]="['/']">Accueil</a>
                    </li>
                    <!-- <li className="nav-item">
                        <a class="nav-link" title="Mon CV en ligne" [routerLink]="['/cv']">CV</a>
                    </li> -->
                    <li className="nav-item">
                        <a class="nav-link" title="Mes projets" [routerLink]="['/projects']">Projets</a>
                    </li>
                    <li className="nav-item">
                        <a class="nav-link" title="Contactez-moi si vous avez des questions" [routerLink]="['/contact']">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

// frontend/src/_components/layouts/Header.tsx
import { NavLink } from "react-router-dom"

function Header() {
  return <header>
    <nav className="navbar navbar-expand-lg navbar-dark">
      <div className="container-fluid">
        <NavLink className="navbar-brand" to="/">FlyArts</NavLink>

        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span className="navbar-toggler-icon"></span>
        </button>

        <div id="mainMenu" className="collapse navbar-collapse">
          <div className="me-auto mb-2 mb-lg-0"></div>
          <ul className="navbar-nav d-flex">
            <li className="nav-item">
              <NavLink className="nav-link" to="/" title="Accueil du site FlyArts">Accueil</NavLink>
            </li>
            <li className="nav-item">
              <NavLink className="nav-link" to="/cv" title="Mon CV en ligne">CV</NavLink>
            </li>
            <li className="nav-item">
              <NavLink className="nav-link" to="/projects" title="Mes projets">Projets</NavLink>
            </li>
            <li className="nav-item">
              <NavLink className="nav-link" to="/contact" title="Contactez-moi si vous avez des questions">Contact</NavLink>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
}

export default Header
