// frontend/src/app/_components/cv/cv.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

import { ProfessionalExperiencesComponent } from './professional-experiences/professional-experiences.component';
import { TrainingsComponent } from './trainings/trainings.component';
import { HobbiesComponent } from './hobbies/hobbies.component';
import { SkillsComponent } from './skills/skills.component';

import * as cvData from '../../../assets/cv.json'

type OpenItem = { type: 'experience' | 'training' | 'skill', id: number } | null

@Component({
  selector: 'app-cv',
  imports: [
    RouterLink,
    ProfessionalExperiencesComponent,
    TrainingsComponent,
    SkillsComponent,
    HobbiesComponent
  ],
  standalone: true,
  templateUrl: './cv.component.html',
  styleUrl: './cv.component.scss'
})
export class CvComponent {
  cvData = cvData;
  openItem: OpenItem = null;

  onExperienceSelected(experienceId: number) {
    this.openItem = { type: 'experience', id: experienceId };
  }

  onTrainingSelected(trainingId: number) {
    this.openItem = { type: 'training', id: trainingId };
  }

  onSkillSelected(skillId: number) {
    this.openItem = { type: 'skill', id: skillId };
  }
}

<div class="container">
	<div class="row">
		<section class="col-sm-12">
			<h1>Ingénieur en développement logiciel et web</h1>
		</section>
		<div class="col-md-3">
			<section id="infos" class="card">
				<div class="card-body">
					<h3>Florent Lavignotte</h3>
					<p>
						<!-- {age} ans<br /> -->
						Permis B avec véhicule
						<br /><br />
						5 allée de la Houn<br />
						64420 ANDOINS
						<br /><br />
						06 70 56 27 10<br />
						<a title="Contactez-moi si vous avez des questions"
							[routerLink]="['contact']">florent.lavignotte&#64;gmail.com</a>
					</p>
					<!-- <hr />
                    <h6>Informations complémentaires</h6>
                    <p>
                        Trésorier d'un club sportif pendant 5 ans.
                    </p> -->
				</div>
			</section>
			<section id="cvVersion">
				<a class="btn btn-danger btn-lg" title="Version imprimable et synthétique" [routerLink]="['cv-papier']"
					target="_blank">Version imprimable</a>
			</section>
		</div>
		<div class="col-md-9">
			<app-professional-experiences [experiences]="cvData.professionalExperiences" [openItem]="openItem"
				(experienceSelected)="onExperienceSelected($event)" />

			<app-trainings [trainings]="cvData.trainings" [openItem]="openItem"
				(trainingSelected)="onTrainingSelected($event)" />

			<app-skills [skills]="cvData.skills" [openItem]="openItem" (skillSelected)="onSkillSelected($event)" />

			<app-hobbies [hobbies]="cvData.hobbies" />
		</div>
	</div>
</div>

// frontend/src/_components/Cv.tsx
import { NavLink } from "react-router-dom";
import Skills from "./cv/website/Skills";
import Trainings from "./cv/website/Trainings";
import ProfessionalExperiences from "./cv/website/ProfessionalExperiences";
import Hobbies from "./cv/website/Hobbies";
import cvData from "../assets/cv.json"
import { ExperienceAnimationContextProvider } from "../_hooks/useCvAnimation";
import "../assets/css/Cv.scss"

export default function Cv() {
  const age = 33;

  return <div className="container">
    <div className="row">
      <section className="col-sm-12">
        <h1>Ingénieur en développement logiciel et web</h1>
      </section>
      <div className="col-md-3">
        <section id="infos" className="card">
          <div className="card-body">
            <h3>Florent Lavignotte</h3>
            <p>
              {age} ans<br />
              Permis B avec véhicule
              <br /><br />
              5 allée de la Houn<br />
              64420 ANDOINS
              <br /><br />
              06 70 56 27 10<br />
              <NavLink to="/contact" title="Contactez-moi si vous avez des questions">florent.lavignotte@gmail.com</NavLink>
            </p>
            {/*
            <hr />
            <h6>Informations complémentaires</h6>
            <p>
              Trésorier d'un club sportif pendant 5 ans.
            </p>
            */}
          </div>
        </section>
        <section id="cvVersion">
          <NavLink className="btn btn-danger btn-lg" to="/cv-papier" title="Version imprimable et synthétique" target="_blank">Version imprimable</NavLink>
        </section>
      </div>
      <div className="col-md-9">
        <ExperienceAnimationContextProvider>
          <ProfessionalExperiences experiences={cvData.professionalExperiences} />

          <Trainings trainings={cvData.trainings} />

          <Skills skills={cvData.skills} />

          <Hobbies hobbies={cvData.hobbies} />
        </ExperienceAnimationContextProvider>
      </div>
    </div>
  </div>;
}
