// frontend/src/app/_components/pages/home/home.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgFor } from '@angular/common';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faArrowRight } from '@fortawesome/free-solid-svg-icons';
import { ProjectComponent } from '../project/project.component';

import * as projects from '../../../../assets/projects.json'

@Component({
  selector: 'app-home',
  imports: [
    RouterLink,
    NgFor,
    FontAwesomeModule,
    ProjectComponent
  ],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent {
  faArrowRight = faArrowRight;

  projects = projects;
}

<div id="home" class="container">
    <div class="row">
        <section class="col-sm-12">
            <div class="jumbotron">
                <h1 class="display-4">FlyArts</h1>
                <p class="lead">Mon petit site perso pour y mettre mes projets, mes passions et un peu de moi en
                    ligne.</p>
            </div>
        </section>

        <section id="portrait" class="col-sm-12 flyarts-section">
            <div class="row">
                <div class="col-md-4">
                    <img class="rounded float-left img-thumbnail" src="assets/img/portrait.jpg" alt="..." />
                </div>

                <div class="col-md-8">
                    <h2>Qui suis-je ?</h2>
                    <p>
                        Je m'appelle Florent Lavignotte et je suis passionné d'informatique depuis le plus jeune age.
                        Tombé dedans avec le premier OS Ms DOS
                        et désireux de créer tous les projets que j'ai en tête, je me suis lancé dans un cursus en
                        Electronique pour ensuite aller dans
                        une école d'ingénieur en informatique spécialisée dans le développement. Aujourd'hui, je réalise
                        enfin mes ambitions et crée des outils
                        en tout genre.
                    </p>
                    <p class="text-right">
                        <a class="btn btn-danger btn-lg" [routerLink]="['/cv']">
                            Accéder à mon CV
                        </a>
                    </p>
                </div>
            </div>
        </section>

        <div class="col-md-12 shadow">
            <div class="row">
                <section class="col-md-6 flyarts-section">
                    <h2>Qu'est ce que FlyArts ?</h2>
                    <p>
                        FlyArts est un site internet que j'ai créé afin de présenter et mettre en avant mes compétences
                        dans le domaine du développement
                        logiciel et web. Ce site a pour but de présenter mes compétences et mes expériences en matière
                        de programmation ainsi que
                        ma personnalité à travers mes passions et loisirs.
                        J'espère pouvoir apporter aux personnes interessées toutes les connaissances que j'ai acquise
                        grâce à mes réalisations.
                    </p>
                </section>
                <section class="col-md-6 flyarts-section">
                    <h2>Pourquoi FlyArts ?</h2>
                    <p>
                        FlyArts était le nom que j'avais choisi pour mon projet de photographie.
                        Avec le temps ce nom est devenu de plus en plus présent dans mes projets.
                        Cela à fini par devenir un peu ma marque de fabrique auprès de mes amis et mes proches.
                        J'ai ainsi donné ce nom au site pour lui donner une personalité propre.
                        L'utilisation de mon nom et mon prénom aurait été trop commun pour un site personnel.
                    </p>
                </section>
            </div>
        </div>

        <section id="projects" class="col-sm-12 flyarts-section">
            <h2>Mes projets en cours</h2>
            <div class="row">
                @for(project of projects; track project.idProject) {
                    @if(project.isDisplay) {
                        <div class="col-md-4">
                            <app-project [project]={project} />
                        </div>
                    }
                }

                <div class="col-md-4">
                    <p id="projectsMore">
                        <a class="btn btn-danger" [routerLink]="['/projects']">
                            <fa-icon [icon]="faArrowRight"></fa-icon>
                        </a>
                    </p>
                </div>
            </div>
        </section>
    </div>
</div>

// frontend/src/_components/Home.tsx
import { NavLink } from 'react-router-dom'
import '../assets/css/Home.scss'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowRight } from '@fortawesome/free-solid-svg-icons'
import { getAllProjects } from '../_api/api'
import Project, { ProjectProp } from './Project'
import { useEffect, useState } from 'react'

export default function Home() {
  const [projects, setProjects] = useState([]);

  useEffect(() => {
    (async () => {
      setProjects(await getAllProjects())
    })();
  }, [])

  return <div id="home" className="container">
    <div className="row">
      <section className="col-sm-12">
        <div className="jumbotron">
          <h1 className="display-4">FlyArts</h1>
          <p className="lead">Mon petit site perso pour y mettre mes projets, mes passions et un peu de moi en ligne.</p>
        </div>
      </section>

      <section id="portrait" className="col-sm-12 flyarts-section">
        <div className="row">
          <div className="col-md-4">
            <img className="rounded float-left img-thumbnail" src="./src/assets/img/portrait.jpg" alt="..." />
          </div>

          <div className="col-md-8">
            <h2>Qui suis-je ?</h2>
            <p>
              Je m'appelle Florent Lavignotte et je suis passionné d'informatique depuis le plus jeune age. Tombé dedans avec le premier OS Ms DOS
              et désireux de créer tous les projets que j'ai en tête, je me suis lancé dans un cursus en Electronique pour ensuite aller dans
              une école d'ingénieur en informatique spécialisée dans le développement. Aujourd'hui, je réalise enfin mes ambitions et crée des outils
              en tout genre.
            </p>
            <p className="text-right">
              <NavLink className="btn btn-danger btn-lg" to="/cv">Accéder à mon CV</NavLink>
            </p>
          </div>
        </div>
      </section>

      <div className="col-md-12 shadow">
        <div className="row">
          <section className="col-md-6 flyarts-section">
            <h2>Qu'est ce que FlyArts ?</h2>
            <p>
              FlyArts est un site internet que j'ai créé afin de présenter et mettre en avant mes compétences dans le domaine du développement
              logiciel et web. Ce site a pour but de présenter mes compétences et mes expériences en matière de programmation ainsi que
              ma personnalité à travers mes passions et loisirs.
              J'espère pouvoir apporter aux personnes interessées toutes les connaissances que j'ai acquise grâce à mes réalisations.
            </p>
          </section>
          <section className="col-md-6 flyarts-section">
            <h2>Pourquoi FlyArts ?</h2>
            <p>
              FlyArts était le nom que j'avais choisi pour mon projet de photographie.
              Avec le temps ce nom est devenu de plus en plus présent dans mes projets.
              Cela à fini par devenir un peu ma marque de fabrique auprès de mes amis et mes proches.
              J'ai ainsi donné ce nom au site pour lui donner une personalité propre.
              L'utilisation de mon nom et mon prénom aurait été trop commun pour un site personnel.
            </p>
          </section>
        </div>
      </div>

      <section id="projects" className="col-sm-12 flyarts-section">
        <h2>Mes projets en cours</h2>
        <div className="row">
          {projects.map((project: ProjectProp) => {
            if (project.visibility)
              return <div className="col-md-4" key={project.idProject}>
                <Project props={project} />
              </div>;
          })}
          <div className="col-md-4">
            <p id="projectsMore">
              <NavLink className="btn btn-danger" to="/projects">
                <FontAwesomeIcon icon={faArrowRight} />
              </NavLink>
            </p>
          </div>
        </div>
      </section>
    </div>
  </div>
}
