// frontend/src/app/_components/projects/projects.component.ts
import { Component } from '@angular/core';

import { ProjectItemComponent } from "./project-item/project-item.component";

import * as jsondevProjects from '../../../assets/dev-projects.json'
import * as jsonOtherProjects from '../../../assets/other-projects.json'

@Component({
  selector: 'app-projects',
  imports: [
    ProjectItemComponent
  ],
  standalone: true,
  templateUrl: './projects.component.html',
  styleUrl: './projects.component.scss'
})
export class ProjectsComponent {
  devProjects = jsondevProjects.projects
  otherProjects = jsonOtherProjects.projects
}

<div class="container">
	<div class="row">
		<section id="project_list" class="col-sm-12 flyarts-section">
			<h1>
				Les projets de développement
				<span class="badge text-bg-danger"><i class="fas fa-code"></i></span>
			</h1>
			<div class="row project-section">
				@for(project of devProjects; track project.idProject) {
				@if(project.isDisplay) {
				<div class="col-md-4">
					<app-project-item [project]="project" />
				</div>
				}
				}
			</div>
		</section>

		<section id="project_list" class="col-sm-12 flyarts-section">
			<h2>
				Les autres projets
			</h2>
			<div class="row project-section">
				@for(project of otherProjects; track project.idProject) {
				@if(project.isDisplay) {
				<div class="col-md-4">
					<app-project-item [project]="project" />
				</div>
				}
				}
			</div>
		</section>

		<section id="more_projects" class="col-sm-12 flyarts-section">
			<h2>Plus de projets</h2>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<p class="card-body">
							<span>Retrouvez tous mes projets de développement directement sur mon GitHub.</span>
							<br /><br />
							<a href="https://github.com/sparky783" target="_blank">
								<i class="fab fa-github"></i>
							</a>
						</p>
					</div>
				</div>
			</div>
		</section>
	</div>
</div>

// frontend/src/_components/Projects.tsx
function Projects() {
  return <div className="container">
    <div className="row">
      <section id="projects" className="col-sm-12 flyarts-section">
        <h1>Mes projets</h1>
        <div className="row">
          {/*echo $projectsHtml;*/}
        </div>
      </section>
      
      <section id="more_projects" className="col-sm-12 flyarts-section">
        <h1>Plus de projets</h1>
        <div className="row">
          <div className="col-md-12">
            <div className="card">
              <p className="card-body">
                <span>Retrouvez tous mes projets de développement directement sur mon GitHub.</span>
                <br /><br />
                <a href="https://github.com/sparky783" target="_blank">
                  <i className="fab fa-github"></i>
                </a>
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
}

export default Projects
