// frontend/src/_components/projects/WebSiteProjects.tsx

export default function WebSiteProjects() {
  return <div className="container">
    <div className="row">
      <section id="projects" className="col-sm-12 flyarts-section">
        <h1>Mes sites web</h1>
        <div className="row">
          {/*projectsList.map((project: ProjectProp) => {
            if (project.isDisplay)
              return <Project key={project.title} props={project} />
          })*/}
        </div>
      </section>
    </div>
  </div>
}

// frontend/src/app/_components/projects/website-projects/website-projects.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-website-projects',
  imports: [],
  templateUrl: './website-projects.component.html',
  styleUrl: './website-projects.component.scss'
})
export class WebsiteProjectsComponent {

}

<div className="container">
    <div className="row">
        <section id="projects" className="col-sm-12 flyarts-section">
            <h1>Mes sites web</h1>
            <div className="row">
                {/*projectsList.map((project: ProjectProp) => {
                if (project.isDisplay)
                return
                <Project key={project.title} props={project} />
                })*/}
            </div>
        </section>
    </div>
</div>
